import { StyleSheet } from '@react-pdf/renderer'

export const styles = StyleSheet.create({
  page: {
    paddingTop: 28,
    paddingBottom: 28,
    paddingHorizontal: 34,
    fontSize: 10.5,
    fontFamily: 'Helvetica',
    color: '#0f172a',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  brand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  logo: {
    width: 26,
    height: 26,
    borderRadius: 6,
  },
  brandTitle: {
    fontSize: 12,
    fontWeight: 700,
  },
  brandSubtitle: {
    marginTop: 2,
    fontSize: 9.5,
    color: '#475569',
  },
  docTitle: {
    fontSize: 16,
    fontWeight: 700,
    marginBottom: 6,
  },
  docMetaRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
    marginBottom: 12,
  },
  chip: {
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
  },
  chipText: {
    fontSize: 9.5,
    color: '#334155',
  },
  section: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 10.5,
    fontWeight: 700,
    marginBottom: 8,
    color: '#0f172a',
  },
  grid2: {
    flexDirection: 'row',
    gap: 10,
  },
  col: { flexGrow: 1, flexBasis: 0 },
  label: { fontSize: 9, color: '#64748b', marginBottom: 2 },
  value: { fontSize: 10.5, color: '#0f172a' },
  muted: { color: '#64748b' },
  table: { borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 12, overflow: 'hidden', marginTop: 6 },
  trHead: { flexDirection: 'row', backgroundColor: '#0b2a7a' },
  th: { paddingVertical: 8, paddingHorizontal: 10, fontSize: 9.5, color: 'white', fontWeight: 700 },
  tr: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: '#e2e8f0' },
  td: { paddingVertical: 8, paddingHorizontal: 10, fontSize: 9.5, color: '#0f172a' },
  tdMuted: { color: '#475569' },
  totalsRow: { flexDirection: 'row', justifyContent: 'flex-end', gap: 14, marginTop: 8 },
  totalsBox: { width: 220, borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 12, padding: 10, backgroundColor: '#f8fafc' },
  totalLine: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  totalStrong: { fontWeight: 700 },
  footer: { position: 'absolute', left: 34, right: 34, bottom: 18, flexDirection: 'row', justifyContent: 'space-between' },
  footerText: { fontSize: 8.5, color: '#64748b' },
  watermark: { position: 'absolute', top: 260, left: 34, right: 34, textAlign: 'center', fontSize: 38, color: '#0b2a7a', opacity: 0.06, transform: 'rotate(-14deg)' },
  sigGrid: { flexDirection: 'row', gap: 10, marginTop: 10 },
  sigBox: { flexGrow: 1, flexBasis: 0, borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 12, padding: 10 },
  sigLine: { height: 1, backgroundColor: '#cbd5e1', marginTop: 24, marginBottom: 6 },
  qrBox: { width: 120, borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 12, padding: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: 'white' },
  qrLabel: { marginTop: 6, fontSize: 8.5, color: '#64748b' },
})

